name: qilu-redis-dev

services:
  redis:
    image: redis:7.2.5-alpine
    container_name: qilu-redis-dev
    restart: unless-stopped
    mem_limit: 512m
    cpus: 1.0
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - type: bind
        source: D:/docker-data/qilu-redis-dev/data
        target: /data
        bind:
          create_host_path: false
      - type: bind
        source: ./redis.conf
        target: /usr/local/etc/redis/redis.conf
        read_only: true
      - type: bind
        source: ../../../.run/redis-local/users.acl
        target: /run/secrets/users.acl
        read_only: true
    healthcheck:
      test: ["CMD", "redis-cli", "--user", "health", "--pass", "health-check", "ping"]
      interval: 3s
      timeout: 2s
      retries: 10
      start_period: 5s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
