dir /data
dbfilename dump.rdb
appendonly no
databases 16
save 60 1
save 300 100
save 60 10000
maxmemory 0
maxmemory-policy noeviction
aclfile /run/secrets/users.acl
protected-mode yes
bind 0.0.0.0
port 6379
logfile ""
